### ISSUE TITLE
onMissingTranslation defaultTranslation variable parsing

### ISSUE THREAD

**Issue by colbyfayock** [ryandrewjohnson/react-localize-redux#101]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Having a variable with a proceeding dollar sign doesn't render as expected when coming from an `onMissingTranslation` callback;

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I forked another issue I found, but it provides the issue.
https://codesandbox.io/s/7rwkqzr7x

If you notice look at the above as is, after clicking "To ES", it creates an exception. This appears to be if you're missing a `defaultLanguage` attribute. That could be expected, though maybe it would make sense to default to the first value of the languages array?

The real issue, if you uncomment the `defaultLanguage` line, you'll notice you no longer get an exception, but the variable isn't properly getting parsed as it would in a typical translation.

**What is the expected behavior?**
`$${variable}` => `$value`

**Which versions of `react` and `react-localize-redux` are you using?**
react: `16.4.0`
react-localize-redux: `5.0.7`

**Comment by thchia** [comment]
@colbyfayock Appreciate I'm a little late here - maybe your codesandbox has changed, but the exception is created because `defaultTranslation` is undefined.

That in turn is because: `<Translate {...props} />` has no children.

**Comment by colbyfayock** [comment]
no worries :) thanks for taking a look

**Comment by ryandrewjohnson** [comment]
@colbyfayock I've published a new version `v3.21.` that should fix this issue. As discussed it will default to the first language for default language when not set. 

Please let me know if this works for you.

**Comment by colbyfayock** [comment]
@ryandrewjohnson it definitely no longer throws an exception, though it doesn't seem to be defaulting to the first value for me 🤔 I updated that code sandbox above to `v3.2.1` to show, when clicking **To ES**, it doesn't error, but doesn't default to `en`: https://codesandbox.io/s/7rwkqzr7x

Additionally, any chance you thought about a solution for the parsing of the variables? as you'll see in that link as well, if you uncomment out the `defaultLanguage` and hit **To ES**, it doesn't substitute the variable value.

**Comment by ryandrewjohnson** [comment]
@colbyfayock  I will need to spend some time to try and create a test that mimics this scenario. I'm not sure when I'll have time to do this as I'm pretty busy right now. If you have some time feel free to investigate, and submit a PR if you find the solution.

**Comment by colbyfayock** [comment]
@ryandrewjohnson no problem, I'll try and take a look - I was originally going to but was having trouble trying to spin up the project in the browser, i'll take another shot at it 👍

**Comment by colbyfayock** [comment]
@ryandrewjohnson got it working, let me know what you think

**Comment by ryandrewjohnson** [comment]
Fixed in #110
