### ISSUE TITLE
wrap getTranslate with reselect

### ISSUE THREAD

**Issue by ieow** [ryandrewjohnson/react-localize-redux#12]
My component which mapstatetoprops getTranslate keep rerendering when ever there is action dispatch.
Could getTranslate wrapped with reselect?

I workaround it by wrapping it before mapping it myself.

**Comment by ryandrewjohnson** [comment]
Is this a component that only has `getTranslate` in mapStateToProps or have you mapped other props as well? If you could provide a code snippet or an example that would be super helpful.

**Comment by ieow** [comment]
The component only map `getTranslate`. I also try map `()=>` which also rerender every time redux state updated.

```
// use reselect (selector) to prevent unnecessary rerendering 
const translateSelector = createSelector(
  state=>state.locale,
  (locale) => getTranslate(locale)
)

// ** map ()=>{} /function cause it trigger component rerender every time redux state update 
const mapStateToProps = state => ({
  locale : state.locale,
  translate : translateSelector(state)
  // translate: getTranslate(state.locale),
});
```

**Comment by ryandrewjohnson** [comment]
Just pushed a release v2.4.0 that fixes this issue.
