### ISSUE TITLE
Avoiding code duplication & Implementation with redux

### ISSUE THREAD

**Issue by vaikoovery** [ryandrewjohnson/react-localize-redux#128]
First of all, thank you so much for such a nice & simple translator package... loving it. <3

Not sure whether its a bug, but I'm facing code duplication issue with & withut redux.
A code sample has been made here: https://codesandbox.io/s/wwpznw5mww

My concern is about duplicating the code in constructor, when I have more translation files available. i.e.

    const { userLanguage } = props
    /* I also have this in Form.js */
    this.props.initialize({
      languages, // this is a duplication?
      translation: globalTranslations, // in other place it could change like "otherTranslations"
      options: { renderToStaticMarkup, userLanguage }
    })`

How do I get rid of it? I literrally has to duplicate it in all functional components, also need to import the relevant files in it.

Please advise a better way to integrate it. (I'm a newbie ;))

I've used `react 16.4.2` and `latest react-localize-redux`.

**Comment by ryandrewjohnson** [comment]
@vaikoovery you should only ever have to call the `initialize` method once in your application. Best practice is to do this when your application is bootstrapping e.g. In your App's componentDidMount or constructor. 

Also in version `v3.4.0` you can now [pass your initialize payload](https://ryandrewjohnson.github.io/react-localize-redux-docs/#working-with-server-side-rendering) directly to `LocalizeProvider` this way you can ensure that initialize will be called before any of your components need it. Moving forward I will most likely start to deprecate the `initialize` method in favour of using the `initialize` prop in `LocalizeProvider`.

**Comment by vaikoovery** [comment]
The reason why I was using initialize in differrent Components is to use multiple json files for differrent components.

Do you recommend using all translations in single file and `Initialize` only once? I assumed that the bundle size can be reduced if I use different json files. Please advise.

**Comment by ryandrewjohnson** [comment]
This is outlined in the [Add translation data](https://ryandrewjohnson.github.io/react-localize-redux-docs/#add-translation-data) section of Getting Started in the docs. 

You need to use [this.props.addTranslation(translations)](https://ryandrewjohnson.github.io/react-localize-redux-docs/#addtranslation). This can be called as many times as you want, and each time will add your new translations. 

I'm going to consider this one closed, and I recommend giving the docs a closer read.
