### ISSUE TITLE
withLocalize makes component rerender and reducer is not added

### ISSUE THREAD

**Issue by subharb** [ryandrewjohnson/react-localize-redux#132]
**Do you want to request a _feature_ or report a _bug_?**
Report a bug

**What is the current behavior?**
Adding withLocalize makes the component to rerender and the reducer is not added since this.props.activeLanguage or this.props.defaultLanguage are undefined on the first render but have value on the second.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here's my index.js:

`import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import { Router, Route , Switch} from 'react-router-dom' //Para coger la URL del navegador
import reducers from './reducers';
import Home from './containers/home/index';
import SingleShow from './containers/event/';
import Checkout from './containers/checkout/index';
import Loading from './components/loading';
import NotFoundPage from './containers/not_found';
import ExtraInfo from './containers/extra_info.js';
import promise from 'redux-promise';
import { ThemeProvider }  from 'styled-components';
import styled from 'styled-components';
import Config from '../src/reducers/config.json';
import Cookies from './containers/cookies';
import ReactGA from 'react-ga';
import createHistory from 'history/createBrowserHistory'
import { LocalizeProvider } from "react-localize-redux";

const history = createHistory()

const createStoreWithMiddleware = applyMiddleware(promise)(createStore);
const store = createStoreWithMiddleware(reducers);

const Wrapper = styled.div`
  background: ${props => props.theme.wrapperBackground}
`;

ReactDOM.render(
  <LocalizeProvider>
  <Provider store={store}>
    <Router history={history}>
      <ThemeProvider theme={Config.theme}>
        <Wrapper>
          <Switch>
            <Route exact path="/" component={Home}/>
            <Route path="/:keyword/:name/:id/:extraparameter?" component={ SingleShow } />
          </Switch>
          <Cookies/>
        </Wrapper>
      </ThemeProvider>
    </Router>
  </Provider>
  </LocalizeProvider>
  , document.querySelector('.general_container'));
`
Then in SingleShow:

`class SingleShow extends Component{
    constructor(props){
        super(props);

        this.show = JsonShows[this.props.match.params.id];
        this.currentUrl = this.props.location.pathname;

        this.props.initialize({
            languages: [
              { name: "Castellano", code: "es" },
              { name: "English", code: "en" }
            ],
            translation: globalTranslations,
            options: { renderToStaticMarkup }
          });
        
        
    }
render(){
        console.log("%c Render single Show", 'background: #222; color: #bada55');
        console.log("activeLanguage",this.props.defaultLanguage);
}
........
export default withLocalize(connect(null, { resetShoppingCart, resetPurchase, resetModal, resetSections, resetSeats } )(SingleShow));
`
**What is the expected behavior?**
It should render only once, when I add `withLocalize` it renders twice like I stated. It shouldnt render twice and this.props.defaultLanguage should have a value.

**Which versions of `react` and `react-localize-redux` are you using?**
react 16
react-localize-redux 3.4.1

**Comment by ryandrewjohnson** [comment]
Please try passing the initialize payload directly to `<LocalizeProvider>`, which is demonstrated in the [server side rendering docs](https://ryandrewjohnson.github.io/react-localize-redux-docs/#working-with-server-side-rendering). This approach works fine client side as well, and I will eventually be updating the docs to communicate this as well when I have time. 

If this doesn't solve the issue I will require a working example in codesandbox that reproduces the issue to help any futher.
