### ISSUE TITLE
Get translation string (raw)

### ISSUE THREAD

**Issue by zannix** [ryandrewjohnson/react-localize-redux#137]
**Do you want to request a _feature_ or report a _bug_?**

Requesting a feature.

**What is the current behavior?**

Translate function returns an object, and there is no way to return a literal string. Often times I need a literal string.

**Which versions of `react` and `react-localize-redux` are you using?**

react-localize-redux 3.5.0, react 16.4.1

I am getting an issue where I have to get a string literal (for passing it into data attributes of dom elements), and an object just won't work in this case.

I could use 

```
<Translate>
        {({ translate }) => (
            translate(path)
        )}
    </Translate>;
```

for every block I need to translate (as mentioned in one of the previous issues here), but I have decided to have the translate function called _doTranslate()_ in a Helper class, which is then included in components and I simply call doTranslate(), because it is much more readable than having to use the arrow function everywhere.

However, with this approach it seems that it is always returning an _object_. Here is the body of the doTranslate function I am using in components:

```
export function doTranslate(path)
{
    return  <Translate>
        {({ translate }) => (
            translate(path)
        )}
    </Translate>;
}
```

Is there something I am missing, and if not, could we see a function to return a string literal?

**Comment by thchia** [comment]
With the pattern you want to use, you need to treat `doTranslate` as a component:

```jsx
function DoTranslate(props) {
  return <Translate>
    {({ translate }) => translate(props.path)}
  </Translate>
}

// later
<DoTranslate path=“...” />
```

**Comment by zannix** [comment]
```
<Translate>
  {({ translate }) => (
    <input placeholder={translate(...)} />
    <input placeholder={translate(...)} />
    // ...
  )}
</Translate>
```

I know I can do it this way, but I'd like to avoid that because of readability. And since this package uses context API I don't see a reason why this feature couldn't be implemented at the level of provider.

Here is the current function that I am using after revising to return a string literal:

```
import ReactDOMServer from 'react-dom/server';
export function translate(path)
{
    let translateComponent = <Translate>
        {({ translate }) => (
            translate(path)
        )}
    </Translate>;

    let renderedString = ReactDOMServer.renderToStaticMarkup(translateComponent);

    return decodeString(renderedString);
}

// renderToStaticMarkup encodes special characters, we have to decode it back
function decodeString(renderedString)
{
    let parser = new DOMParser;
    let dom = parser.parseFromString(
        '<!doctype html><body>' + renderedString,
        'text/html');
    return dom.body.textContent;
}
```

**Comment by thchia** [comment]
> And since this package uses context API I don't see a reason why this feature couldn't be implemented at the level of provider.

I don't quite follow this - when using Context, you still need to access `Context.Consumer`, this is what is happening in the `Translate` component, so it looks like there is no way to avoid the readability issues you encounter.

**Comment by ryandrewjohnson** [comment]
Based on @thchia's comments closing this one.
