### ISSUE TITLE
Cannot read property 'map' of undefined when running initialize()

### ISSUE THREAD

**Issue by vascojm82** [ryandrewjohnson/react-localize-redux#147]
Hi,

I was able to make react-redux-localize work and it does so for as long as I navigate my React single page app from the navigation links(using React-Router 4). I do my initialization from the Homepage component and everything works fine when navigating from that component to Login but if I hit re-load on the browser from the SignIn component, the whole thing breaks because I basically loose the whole state on Redux, it goes back to empty.  In order to solve this issue I thought of passing the languages array and options as props to my SignIn  component and using mapDispatchToProps to have an init function that dispatches a call to 'initialize' with the languages array and some options as parameters in the case the 'activeLanguage' is undefined.  That I thought would restore the state in Redux and would get my page to load fine with translations and everything if the user hit the reload button on the browser.  The issue I'm having is that I'm getting the following error:

![image](https://user-images.githubusercontent.com/18554186/52877831-2115ae80-3129-11e9-8a44-d34a6dc084fb.png)

I'm doing the initialize() from the Home component.

**Comment by ryandrewjohnson** [comment]
It's hard to say for sure without seeing a working example, but you need to ensure you are calling initialize before attempting to access any translation data. In your case I would recommend calling initialize from App.js to ensure that your translations are initialized before any specific page is accessed. 

Also I recommend actually initializing by passing your data to [LocaizeProvider's initialize prop](https://ryandrewjohnson.github.io/react-localize-redux-docs/#working-with-server-side-rendering), which is the required format when dealing with server side rendering. This will most likely be the preferred method for initialization in future versions.

**Comment by vascojm82** [comment]
I moved the initialize call out of home.js to App.js, which is also where I have my router but it doesn't work correctly, here's my App.js:

```
import React from 'react';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import store from './store/store';
import { Provider } from "react-redux";
import { LocalizeProvider } from 'react-localize-redux';
import { renderToStaticMarkup } from 'react-dom/server';
import { initialize } from 'react-localize-redux';
import { withLocalize } from 'react-localize-redux';
import Favicon from 'react-favicon';
import NavBar from './components/common/NavBar/SomeNavBar';
import Footer from './components/common/Footer/SomeFooter';
import HomePage from './Pages/Home/home';
import Login from './Pages/Login/index';
import CreateNewUser from './Pages/Login/index';

class App extends React.Component{
  constructor(props){
    super(props);
  }

  componentWillMount(){
    let defaultLanguage = 'en';
    let languages = [
      { name: 'English', code: 'en' },
      { name: 'Spanish', code: 'es' }
    ];
    let options = { renderToStaticMarkup };

    this.setState({
      defaultLanguage: defaultLanguage,
      languages: languages,
      options: options
    }, () => {
      initialize({
        languages: this.state.languages,
        options: this.state.options
      });
    })
  }

  render(){
    return(
      <Provider store={store}>
        <LocalizeProvider store={store}>
          <Favicon url="/img/favicon.ico" />
          <Router>
            <React.Fragment>
              <NavBar />
              <Switch>
                <Route exact path="/" component={ () => <HomePage lang={this.state.defaultLanguage}  /> } />
                <Route exact path="/signin/:lang" render={ (props) => <Login  {...props} /> } />
                <Route exact path="/createnew/:lang" render={ (props) => <CreateNewUser  {...props} /> } />
              </Switch>
            </React.Fragment>
          </Router>
          <Footer />
        </LocalizeProvider>
      </Provider>
      );
  }
 }

 export default withLocalize(App);
```
And here's a screenshot of what I get for the homepage on the browser:

![image](https://user-images.githubusercontent.com/18554186/52877044-e90d6c00-3126-11e9-92b9-98953e4b0ae5.png)

Note: If I do initialize() from the home.js component, it works just fine, even when going to other routes(components) for as long as it is using the links in the homepage itself. If I try typing a route to a different component in the browser url it breaks. When I do initialize() from App,js, the languages array and options never get loaded to the store so none of the pages get rendered with translations as you can see in the screenshot above.

**Comment by vascojm82** [comment]
I made it work adding the initialize to the LocalizeProvier component:

`<LocalizeProvider store={store} initialize={{ languages: languages, options: options}}>`

**Comment by vascojm82** [comment]
After adding:

`<LocalizeProvider store={store} initialize={{ languages: languages, options: options}}>`

The route loads and the page gets all of its structure, labels, textboxes and the translations works fine but it craps out at some point and the rest of the styling doesn't get loaded so the page renders with none of the styling and images.  I get this error on the console:

 
![image](https://user-images.githubusercontent.com/18554186/52961239-7f7ca000-3368-11e9-8408-f3dd253af6be.png)

**Comment by ryandrewjohnson** [comment]
This issue does not appear to be related to the original issue. To avoid muddying up this thread for future users I'm going to close this. If you feel there is a new issue please open a new issue, and please follow the issue template.

In addition looking at the console errors it doesn't appear to be related to anything specific to this library. The errors are stemming from `jquery.min.js` and `bootstrap.min.js`. The remaining issues appear to be lint issues.
