### ISSUE TITLE
Missing Localized key in Containers

### ISSUE THREAD

**Issue by jaimemateo** [ryandrewjohnson/react-localize-redux#15]
Dear Ryan,

First of all congrats for the package, it is what I was looking for. After installation I made a trial with an example translation right in my store configuration and it worked pretty well:

### configureStore.js

	  const configureStore = () => {
	  const persistedState = loadState();
	  const store = createStore(
	    rootReducer,
	    persistedState);
	
	  store.subscribe(throttle(() => {
	    saveState({
	    });
	  }, 1000));
	
	  store.dispatch(setLanguages(['en', 'es', 'fr'], 'en'))
	
	  const locales = {
	    "welcome": {
	      "greeting": [
	        "Hello ${ name }!",
	        "Bonjour ${ name }!",
	        "Hola ${ name }!"
	      ]
	    },
	  }
	  store.dispatch(addTranslation(locales))
	
	  return store;

This was translating the words in my SignupContainer. However, once I want to modularize this and move store.dispatch(addTranslation(locales)) somewhere else... the error Missing Localize key appears. For example, I would like to translate each module text in the same module file like follows:

### SignupContainer.js
	import React, { Component } from 'react';
	import { connect } from 'react-redux'
	import { Link } from 'react-router-dom';
	import { getTranslate, getActiveLanguage } from 'react-localize-redux'
	import configureStore from '../../store/configureStore'
	import { addTranslation } from 'react-localize-redux'
	
	const store = configureStore()
	
	const signup = {
	  "welcome": {
	    "greeting": [
	      "Hello ${ name }!",
	      "Bonjour ${ name }!",
	      "Hola ${ name }!"
	    ]
	  },
	  "info": {
	    "greeting": [
	      "Hello",
	      "Bonjour",
	      "Hola"
	    ]
	  }
	}
	store.dispatch(addTranslation(signup))
	
	
	class SignupContainer extends Component {
	  render(translate, currentLanguage) {
	    return (
	      <div>
	        <h1>{ this.props.translate('welcome.greeting') }</h1>
	        <p>This is a Signup Form</p>
	        <li><Link to="/login">Go to Login Page</Link></li>
	      </div>
	    )
	  }
	}
	
	const mapStateToProps = state => ({
	  translate: getTranslate(state.locale),
	  currentLanguage: getActiveLanguage(state.locale).code
	})
	
	export default connect(mapStateToProps)(SignupContainer);

However in this case I'm getting **Missing localized key: welcome.greeting**. I'm new to Redux so maybe it is not something related to your package but for me it looks like the same thing though...

Thanks in advance!

**Comment by ryandrewjohnson** [comment]
Thanks for the kind words. From the snippets everything seems to look right...

Any chance you can point me to a working example somewhere? Also if I could get a look at your rootReducer setup where you include `localeReducer`.

**Comment by ryandrewjohnson** [comment]
Also couple other things I noticed.... again until I see the entire source some of these things are assumptions.

1. It looks like you are trying to include your `configureStore` function in each component, which means that this logic will be run multiple times. When creating your store you're going to want to do that only once during your app's session. Usually you do this work in your main `index.js` file that bootstrap's your application. Same goes for calling `setLanguages` you usually want to call this only once when the app starts up, unless you are dynamically adding new languages at some point in your app.

2. In this line `store.dispatch(setLanguages(['en', 'es', 'fr'], 'en'))` you can exclude the second `en` argument. By default `setLanguages` will use the first language in the array as default - you only need to pass this argument if you want your default language to be `es` or `fr` in your case.

**Comment by jaimemateo** [comment]
Of course Ryan,

I'm writing down here the complete configurationStore, the rootReducer and Root component. As you can see, the configurationStore should be initialized only in Root.js component. But then, when I have to store.dispacth(addTranslate) in my modules, I'm importing again configureStore which is a function returning the store:

### configStore.js

        import { createStore } from 'redux'
	import { loadState, saveState } from './localStorage'
	import throttle from 'lodash/throttle'
	import rootReducer from '../Root/reducers'
	import { setLanguages, addTranslation } from 'react-localize-redux'
	
	const configureStore = () => {
	  const persistedState = loadState();
	  const store = createStore(
	    rootReducer,
	    persistedState);
	
	  store.subscribe(throttle(() => {
	    saveState({
	    });
	  }, 1000));
	
	  store.dispatch(setLanguages(['en', 'es', 'fr'], 'en'))
	
	  const locales = {
	    "welcome": {
	      "greeting": [
	        "Hello ${ name }!",
	        "Bonjour ${ name }!",
	        "Bonjour ${ name }!"
	      ]
	    },
	    "info": {
	      "greeting": [
	        "Hello",
	        "Bonjour"
	      ]
	    }
	  }
	  store.dispatch(addTranslation(locales))
	
	  return store;
	};
	
	export default configureStore;


### rootReducer.js


       import { combineReducers } from 'redux'
       import { localeReducer } from 'react-localize-redux'
	
	const rootReducer = combineReducers({
	  locale: localeReducer
	})
	
	export default rootReducer

###  Root.js

	import React, { Component } from 'react';
	import { Route, BrowserRouter, Switch } from 'react-router-dom';
	import { Provider } from 'react-redux'
	
	import SignupContainer from '../Modules/Signup/SignupContainer'
	import LoginContainer from '../Modules/Login/LoginContainer'
	
	import configureStore from '../store/configureStore'
	const store = configureStore()
	
	class Root extends Component {
	  render() {
	    return (
	      <Provider store={store}>
	        <BrowserRouter>
	          <Switch>
	            <Route exact path='/' component={ LoginContainer } />
	            <Route path='/login' component={ LoginContainer } />
	            <Route path='/signup' component={ SignupContainer } />
	            <Route component={()=>(<div>NoMatch</div>)}/>
	          </Switch>
	        </BrowserRouter>
	      </Provider>
	    );
	  }
	}
	
	export default Root

If this is still not enough information I will try to create a demo in plunkr or one of those. Thanks a lot!

**Comment by ryandrewjohnson** [comment]
Sorry I should have noticed this sooner...

So in your SignupContainer.js you don't need direct access to the store as this component is already `connected`. You just need to pass `mapDispatchToProps` as the second argument to `connect`. This is where you need to add `addTranslation`. 

I recommend reading [connect](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) docs to familiarize yourself with `mapDispatchToProps` as this is how you should be connecting any of the redux actions you want to dispatch in your app.

Like so...

```javascript
import { setLanguages, addTranslation } from 'react-localize-redux'

class SignupContainer extends Component {
  
  componentDidMount() {
     // now your component has access to addTranslation on props and because it was passed to 
    // connect this will handle dispatching this action 
     this.props.addTranslation(signup);
  }
  render(translate, currentLanguage) {
    return (
      <div>
        <h1>{ this.props.translate('welcome.greeting') }</h1>
        <p>This is a Signup Form</p>
        <li><Link to="/login">Go to Login Page</Link></li>
      </div>
    )
  }
}

const mapStateToProps = state => ({
  translate: getTranslate(state.locale),
  currentLanguage: getActiveLanguage(state.locale).code
})

// this is shorthand version of mapDispatchToProps... 
const mapDispatchToProps = { addTranslation };

export default connect(mapStateToProps, mapDispatchToProps)(SignupContainer);
```

Lastly I would recommend having a look at the the [dynamic-routes](https://github.com/ryandrewjohnson/react-localize-redux/tree/master/examples/dynamic-routes) example included in the repo. Here I call `addTranslation` from my route's `onEnter`callback, and split up my translations by section. This is purely preference as you can split your translations up however you like -- in your example it looks like you're including translations with components, which is ok, but you will want to avoid connecting too many components. See [passing translations to child components](https://github.com/ryandrewjohnson/react-localize-redux#pass-multiple-translations-to-child-components) for a different strategy.
