### ISSUE TITLE
Translate string in saga file

### ISSUE THREAD

**Issue by marknguyen85** [ryandrewjohnson/react-localize-redux#151]
Hi there.
I'm using redux and saga and using translation for the component and it's great but I don't know how to translate the string in the saga file without the Component.

In the saga file I can access localizeReducer that is passed through the state but I cannot find any function to translate.

**Comment by yoieh** [comment]
Why do you need to translate in side if a saga? 

Im usually just saving the translation ID to redux, then using the translation component inside of my component. 

Get the translation ID with `mapStateToProps` and use it with `<Translate id={this.props.myIdTranslation} />`

**Comment by marknguyen85** [comment]
> Why do you need to translate in side of a saga?
> 
> Im usually just saving the translation ID to redux, then using the translation component inside of my component.
> 
> Get the translation ID with `mapStateToProps` and use it with `<Translate id={this.props.myIdTranslation} />`

i have some case must check as network, etc..... and throw message before call services

**Comment by dmitrykrylov** [comment]
> Why do you need to translate in side of a saga?

For instance, you could listen for all actions ending with `_FAILURE` or `_SUCCESS` and push toast-notifications.

> In the saga file I can access localizeReducer that is passed through the state but I cannot find any function to translate.

You just need a selector:

```js
import { put, select } from 'redux-saga/effects';
import Notifications from 'react-notification-system-redux';
import { getTranslate } from 'react-localize-redux';

export function* mySaga({ type }) {
  const localizeState = yield select(state => state.localize);
  const translate = getTranslate(localizeState);
  yield put(Notifications.show({ title: translate('notifications.success') }, 'success'));
}
```

**Comment by marknguyen85** [comment]
> > Why do you need to translate in side of a saga?
> 
> For instance, you could listen for all actions ending with `_FAILURE` or `_SUCCESS` and push toast-notifications.
> 
> > In the saga file I can access localizeReducer that is passed through the state but I cannot find any function to translate.
> 
> You just need a selector:
> 
> ```js
> import { put, select } from 'redux-saga/effects';
> import Notifications from 'react-notification-system-redux';
> import { getTranslate } from 'react-localize-redux';
> 
> export function* mySaga({ type }) {
>   const localizeState = yield select(state => state.localize);
>   const translate = getTranslate(localizeState);
>   yield put(Notifications.show({ title: translate('notifications.success') }, 'success'));
> }
> ```

So good, thanks for support.
