### ISSUE TITLE
Add useTranslate() hook

### ISSUE THREAD

**Issue by dmitrykrylov** [ryandrewjohnson/react-localize-redux#152]
It would be really great to have a hook for getting localization data. And the simplest implementation could look like this:
```js
// @flow
import React, { useContext } from 'react';
import { LocalizeContext, type LocalizeContextProps } from './LocalizeContext';

export function useTranslate(): LocalizeContextProps {
  return useContext(LocalizeContext)
}
```

I didn't test it yet, but it should work this way:
```js
const MyComponent = () => {
  const { translate } = useTranslate()
  return <div>{translate('key')}</div>
}
```

@ryandrewjohnson any proposals on this feature?

UPD. I tried to switch from `withLocalize` to `useTranslate` in Books page of the demo app but I can't run it because there is no `react-localize-redux` in dependencies. @ryandrewjohnson how do you handle running the demo? Also, any ideas how to test hook in this case? The only thing we need is to be sure that `useTranslate` returns our context value.

<img width="1184" alt="Screen Shot 2019-04-03 at 00 14 45" src="https://user-images.githubusercontent.com/14343880/55436668-963c2680-55a5-11e9-89e7-9197871b7f6e.png">

**Comment by ryandrewjohnson** [comment]
@dmitrykrylov see the v4.0 Roadmap #140. This captures exactly the functionality you're describing. I started the work, but I've since become busy so had to put it on hold. If you're interested in contributing let me know.

**Comment by dmitrykrylov** [comment]
> v4.0 Roadmap #140

> If you're interested in contributing let me know.

That's why I'm here. I would like to submit a pr, but can't come up with how to do tests or demo for this case

**Comment by ryandrewjohnson** [comment]
@dmitrykrylov if you want to contribute I recommend that you work off of the branch that was created for v4.0, which is outlined in #140. This hook will only be rolled out as part of a much larger release which includes all the scope items listed in the issue. Any help is appreciated, but if you are going to take on the hooks portion I recommend having a look at the v4  branch I started as reference, as I updated the library to use hooks internally, and wrote tests for them. 

I'm going to close this issue in favour of moving conversation over to the #140

**Comment by raheelshan** [comment]
I have created a pretty simple hook for that.


    import { useContext } from 'react';
    import { LocalizeContext } from 'react-localize-redux';

    const useTranslate = () => {

    const context = useContext(LocalizeContext);
    const { translate } = context;

    if (!context) {
        throw new Error('useTranslate must be used within a LocalizeProvider')
    }

    return translate
    };

    export default useTranslate;

Use it like this.

     const translation = useTranslate();

    <Text>{translation('key')}</Text>
