### ISSUE TITLE
Options of select lists are not being translated

### ISSUE THREAD

**Issue by Nodirbek3d** [ryandrewjohnson/react-localize-redux#154]
react-localize-redux is not translating options of select element.
Code sample:
`<select className="form-control" id="selectCity">
                                <option value="Select city"><Translate id="cityselector.selectcity">Select your city</Translate></option>
                                <option value="andijan"><Translate id="cityselector.andijan">Andijan</Translate></option>
                                <option value="fergana"><Translate id="cityselector.fergana">Fergana</Translate></option>
                                <option value="tashkent"><Translate id="cityselector.tashkent">Tashkent</Translate></option>
                                <option value="samarkand"><Translate id="cityselector.samarkand">Samarkand</Translate></option>
                                <option value="namangan"><Translate id="cityselector.namangan">Namangan</Translate></option>
                            </select>`

I use single translation files:
` "cityselector":{
    "header": "Закажи еду на доставку!",
    "selectcity": "Выберите город",
    "andijan":"Андижан",
    "tashkent":"Ташкент",
    "fergana": "Фергана", 
    "samarkand":"Самарканд",
    "namangan":"Наманган",
    "orderfood":"Заказать!"
  }`
The result is options with text `object Object`

using react v16.8.4 and react-localize-redux 3.5.2

**Comment by Roshanalexander** [comment]
Hey @Nodirbek3d,
Assuming you closed this issue because you found a solution. If you did, please share the solution. I ran into a similar issue. I'm getting ``` object object ``` inside Select option.

**Comment by Nodirbek3d** [comment]
Hey @Roshanalexander, I found a work around to this:
`import { withLocalize, Translate } from 'react-localize-redux';
 <Translate>{({ translate }) => <option value="none">{translate("cities.sel")}</option>}</Translate>
`

**Comment by Roshanalexander** [comment]
it worked! Thanks...
