### ISSUE TITLE
Incorrect return type definition for onMissingTranslationFunction

### ISSUE THREAD

**Issue by BobaFatale** [ryandrewjohnson/react-localize-redux#156]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**
the TypeScript definition for `onMissingTranslationFunction` is throwing an error when `defaultTranslation` is returned by the function because the return type is `string` but the type of `defaultTranslation` is `LocalizedElement`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

https://codesandbox.io/s/9y6rmj1xkr?fontsize=14&module=%2Fsrc%2Futils.ts

**What is the expected behavior?**
I believe that the proper return type of `onMissingTranslateFunction` should be `string | LocalizedElement`

**Which versions of `react` and `react-localize-redux` are you using?**
`"react": "^16.8.6"`
`"react-localize-redux": "^3.5.2"`

**Comment by ryandrewjohnson** [comment]
@BobaFatale thanks for catching. If you have the time to submit a PR for this it would be greatly appreciated.

**Comment by ryandrewjohnson** [comment]
Fixed in #157.
