### ISSUE TITLE
There is any plan to adapter the latest react version?

### ISSUE THREAD

**Issue by ceu** [ryandrewjohnson/react-localize-redux#166]
i'm  using the react-localize-redux --- "3.5.3"   react ------ "16.4.1 "

if i update the react version to 16.8.6 ,  the react-localize-redux could't used!

and the translate have  delay in some situation, should be click the browser refresh , the translate  will be Ok

@ryandrewjohnson

**Comment by ryandrewjohnson** [comment]
Closing due to lack of details in the issue. An updated version is in the works and is being tracked in #140
