### ISSUE TITLE
Will react localize redux package set the lang attribute in <html> element ?

### ISSUE THREAD

**Issue by lavanya-kuda** [ryandrewjohnson/react-localize-redux#167]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**

Will react localize redux package set the lang attribute in <html> element ?

**What is the expected behavior?**

As per accessibility issues, we see Html element is not set with a lang attribute.

**Comment by ryandrewjohnson** [comment]
This would be up to you to set this attribute as react-localize-redux is completely agnostic when it comes to setting up the languages you're supporting. This would be a matter of updating the html lang attribute every time the active language changes. The implementation of that is outside the scope of this library though as it really depends on how your app is setup. e.g. Is the <html> element part of your react app vs not
