### ISSUE TITLE
Specify in the documentation that component that holds `props.initialize` should be a class

### ISSUE THREAD

**Issue by vikdotdev** [ryandrewjohnson/react-localize-redux#170]
First of all keep in mind that I'm a react newb. I wasted a good bit of time before realizing that `props.initialize()` can't be used inside function component, is it really the case?

As react leans more towards function components I feel like it should be stated somewhere in the docs that this package will only work with class holding the initializer and that the function will not work.

**Which versions of `react` and `react-localize-redux` are you using?**
react - 16.8.6
reat-localize-redux - 3.5.3

**Comment by goeaway** [comment]
Not sure what issue exactly you were having but when I tried this within a function component in Typescript I was getting [this error](https://reactjs.org/docs/error-decoder.html/?invariant=185). 

I managed to get around this by placing the `initialize` call in a `useEffect()` hook:

```
import * as React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { withLocalize, LocalizeContextProps, Translate } from "react-localize-redux";
import * as enTrans from "../translations/en.json";
import * as nlTrans from "../translations/nl.json";

export interface AppProps extends LocalizeContextProps {
}

const App: React.FC<AppProps> = ({ initialize, addTranslationForLanguage }) => {
    React.useEffect(() => {
        initialize({
            languages: [
                { name: "English", code: "en" },
                { name: "Dutch", code: "nl" }
            ],
            options: { renderToStaticMarkup }
        });
    
        addTranslationForLanguage(enTrans, "en");
        addTranslationForLanguage(nlTrans, "nl");
    }, []); // <-- this empty array stops the hook being called every time the comp rerenders

    return (
        <div>
            <Translate id="greeting" />
        </div>
    );
}

export default withLocalize(App);
```

I'm fairly new to hooks myself so there might be a preferred implementation, but this at least got my app working

**Comment by ryandrewjohnson** [comment]
There is no dependency that requires you to use class components vs functional components. Following the current docs you would just use the [withLocalize](https://ryandrewjohnson.github.io/react-localize-redux-docs/#withlocalize) HOC, which is demonstrated in the docs using both class and functional components.
