### ISSUE TITLE
Callback when translation doesn't exist...

### ISSUE THREAD

**Issue by eliomaria** [ryandrewjohnson/react-localize-redux#23]
Is there a way i can use a callback function when one of the translations doesn't exist?

**Comment by ryandrewjohnson** [comment]
This doesn't currently exist ...

Can you tell me a little more about the use case for this feature?

**Comment by eliomaria** [comment]
Every time a translation doesn't exist i send it to the server, so it can be translated in the backoffice. What i was suggesting was a callback to trigger when you return the "Missing localized key:".

My workaround for that was:

```
const Translate = ({tag, vars, translate, currentLanguage}) => {
    let result = translate(tag);
    if (result.indexOf("Missing localized key:") > -1) {

        InfoRequests.postMissingTranslation(tag, currentLanguage, vars).then(result=>{
            console.log('%c The Tag ' + tag + ' doesn't exists. It was added to the backoffice ', 'background: #FF0000; color: #FFF');
        });

        return <span style={{color: "#FF0000"}}>{tag}</span>
    }
    return <span>{result}</span>
};
```

**Comment by ryandrewjohnson** [comment]
I think I could add a callback option that can be set during the initialize action easy enough. What would be the expected arguments passed to the callback? I'm thinking translation key, and the current language code.

**Comment by eliomaria** [comment]
Yes, all i can think of is the key to translate and the current language. I send some extra stuff to help the translation, like:
- if there is vars in the key so the user can translate and see witch vars the translation can take.
- the URL to the page where the translation takes place.

But of course this is outside "react-localize-redux", just putting here to send some ideas to people who want to use the callback.

Thank you for the great Package btw... was able to implement translations in my platform in about 5 minutes ;)

**Comment by ryandrewjohnson** [comment]
@eliomaria this feature has been added #25. Let me know if this works for you.

https://github.com/ryandrewjohnson/react-localize-redux/releases/tag/v2.10.0

**Comment by ryandrewjohnson** [comment]
@eliomaria I haven't heard back on the update, so I'm going to assume its working and close for now.
