### ISSUE TITLE
How to correctly connect Translate to multiple components

### ISSUE THREAD

**Issue by rohan-buchner** [ryandrewjohnson/react-localize-redux#27]
I know this is not the exact right forum for this... but if you could please advise :|
(I realize this issue isn't pertaining to this framework... but I'm struggling with what seems to be a more complicated (due to lack of know how), situation)

https://stackoverflow.com/questions/46319874/redux-localization

**Comment by rohan-buchner** [comment]
I may or may not have solved this... :|

**Comment by ryandrewjohnson** [comment]
Let me know if you have any questions.
