### ISSUE TITLE
Add alternative to use the translation without connector to the components

### ISSUE THREAD

**Issue by stefensuhat** [ryandrewjohnson/react-localize-redux#3]

**Comment by ryandrewjohnson** [comment]
I'm not 100% sure what the request is, but I am working an update to the translate function that would allow you to easily pass multiple translations down to a child component, but the parent component would still need to be connected. I'm hoping to have this new feature ready by end of week.

In meantime if you want to provide some more detail on your issue I might be able to better answer.

**Comment by ryandrewjohnson** [comment]
I have added the new feature I mentioned. See [Pass multiple translations to child components](https://github.com/ryandrewjohnson/react-localize-redux#pass-multiple-translations-to-child-components).

I'm also going to mark this as closed since there's been no details added to this issue.

**Comment by ieow** [comment]
I think he meant component connected with getTranslate would rerender on every action dispacthed.
I tried using selector to prevent unnecessary rerendering.
`const translateSelector = createSelector(
  state=>state.locale,
  (locale) => getTranslate(locale)
`
)
