### ISSUE TITLE
Feature Request: initialize() with array of objects

### ISSUE THREAD

**Issue by Landish** [ryandrewjohnson/react-localize-redux#30]
Hi @ryandrewjohnson,

I'm opening this issue about the topic, which I started in #21.

The _problem_ in current solution is that, you can only initialize locales with _language codes_.

```js
import { initialize } from 'react-localize-redux';

const languages = ['en', 'fr', 'es'];
store.dispatch(initialize(languages));
```
And with this scenario, it is bit hard to get the _current language name_. 

I had to implement my own util functions to display "English" in a `<LocaleSwitcher />` component, which is simple dropdown with `select` tag.

Something like this:

```js
const locales = [
  {
    code: 'en',
    name: 'English',
  },
  {
    code: 'fr',
    name: 'French',
  },
  {
    code: 'es',
    name: 'Spanish',
  },
];

// localeByCode('es') => { code: 'es', name: 'Spanish' }
// this util function is used then <LocaleSwticher /> component
// to display the current language name.
const localeByCode = (code, locales) => {
  const locale = locales.filter(l => l.code === code)[0];
  return locale ? locale : locales[0];
};

// => ['en', 'fr', 'es']
const localeCodes = locales.map(l => l.code);
store.dispatch(initialize(localeCodes));
```

What i'm proposing is, that to have an ability to pass an **array of objects** in `initialize` action creator.

And the API would look something like this:

```js
import { initialize } from 'react-localize-redux';

const languages = [{
    code: 'en',
    name: 'English',
  },
  {
    code: 'fr',
    name: 'French',
  },
];

store.dispatch(initialize(languages));
```

Also, in this case, `getLanguages()` and `getActiveLanguage()` should return different values:

```
// getActiveLanguage() => { code: 'en', name: 'English', active: true } 
// Instead of: 
// getActiveLanguage() => { code: 'en', active: true }

// getLanguages() => 
[{ code: 'en', name: 'English', active: true }, { code: 'fr', name: 'French', active: false }]
// Instead of: 
// getLanguages() => [{ code: 'en', active: true }, { code: 'fr', active: false }]
```

Other actions should not be changed, as long as, they don't need to know about that `name` key.

**Comment by ryandrewjohnson** [comment]
@pa Thanks this level of detail really helps. I will try and have a look at this tonight, but also feel free to submit a PR if you think it’s sokething you’d like to work on.

**Comment by Landish** [comment]
Will do my best on PR.

**Comment by ryandrewjohnson** [comment]
@Landish sorry nuked my comment by accident... doing GitHub from phone always a poor choice 😜.

Yea if you have time I’d appreciate the PR. -  I think it may be as easy as doing a check on type in the initialize action 1st arg. E.g: If array contains strings than just language codes, and if object with code and name prop use that. The project uses Flow for types and also contains a TypeSxript definition that would need to be updated along with unit tests.

Let me know if you have any questions.

**Comment by ryandrewjohnson** [comment]
@Landish did you still want to work on this? If not I have some time tonight where I could get a start on it. Let me know.

**Comment by Landish** [comment]
@ryandrewjohnson , Yeah, that would be great. I had no free time to work on it, since I opened this issue. Deadlines are killing me :(

**Comment by ryandrewjohnson** [comment]
@Landish just pushed this feature in latest [release](https://github.com/ryandrewjohnson/react-localize-redux/releases/tag/v2.13.0). Let me know if it works, and if so please close the issue.

**Comment by Landish** [comment]
@ryandrewjohnson I've updated to the latest version. Works excellent. Thanks 🙏
