### ISSUE TITLE
Can't setActiveLanguage

### ISSUE THREAD

**Issue by Vict0rSch** [ryandrewjohnson/react-localize-redux#32]
I have the `locale` reducer set :

```javascript
import { localeReducer as locale } from 'react-localize-redux';
combineReducers({ locale, otherReducers});
```

The languages initialized:

```javascript
const languageToUse = 'en';
const languages = ['en', 'fr'];
store.dispatch(initialize(languages));
const json = require('../static/texts/global.locale.json');
store.dispatch(addTranslation(json));
store.dispatch(setActiveLanguage(languageToUse));
```

And the function mapped to the props:

```javascript
import { getTranslate, getActiveLanguage, setActiveLanguage } from 'react-localize-redux';

function mapStateToProps(state) {
    return {
      restOfState: state.restOfState,
      translate: getTranslate(state.locale),
      currentLanguage: getActiveLanguage(state.locale).code,
      setActiveLanguage: setActiveLanguage,
    };
  }

  export default mapStateToProps;
```

However calling `this.props.setActiveLanguage('fr')` in a connected component does not change anything  (logging `this.props.currentLanguage` ). Is this an issue or am I missing something?

**Comment by ryandrewjohnson** [comment]
@Vict0rSch a couple questions?

1. What version of the library are you running?
2. Any chance you can post a working example on https://codesandbox.io?

I just did a quick test with latest version of library and `setActiveLanguage` seems to be working as expected.

**Comment by Vict0rSch** [comment]
From my `package.json` : `"react-localize-redux": "^2.13.0"`

(codesandbox gives me an internal server error running my repo, but it is there:[https://github.com/Vict0rSch/oop/tree/master/react](https://github.com/Vict0rSch/oop/tree/master/react))

I don't really know what to check more. Logging `this.props.setActiveLanguage` gives me:

```javascript
ƒ setActiveLanguage(languageCode) {
  return {
    type: SET_ACTIVE_LANGUAGE,
    payload: { languageCode: languageCode }
  };
}
```
which seems to be expected and the `languageCode` I use, (`fr`) is indeed the one I defined in `initialize(languages)`

**Comment by Vict0rSch** [comment]
I think I know, it's not a state it's a `dispatch`.

How do I integrate the setActiveLanguage action into 
```javascript
function mapDispatchToProps(dispatch) {
  return bindActionCreators(actionCreators, dispatch);
}
```
