### ISSUE TITLE
How can I use translate in TypeScript project?

### ISSUE THREAD

**Issue by Codeluck** [ryandrewjohnson/react-localize-redux#33]
I am just wondering how can I use `translate:getTranslation(state.locale)` in TypeScript *.tsx component?
Looks like TypeScript definition of `getTranslation` requires at least 2 parameters: 

`export type Translate = (value: TranslateValue, data: TranslatePlaceholderData, options?: Options) => LocalizedElement|LocalizedElementMap;`

So what is `data: TranslatePlaceholderData` for? I am just expecting to only call `this.props.translate('foo')` somewhere in my TSX markup.

Thanks in advance and sorry if my questions are too noob.

**Comment by ryandrewjohnson** [comment]
@Codeluck this was an error in the type file - the `data: TranslatePlaceholderData` should be optional. I have updated the type definition and pushed the change. Let me know if this fixes your're issue.

**Comment by ryandrewjohnson** [comment]
@Codeluck I've just done another release as I took the time to overhaul the flow types, and noticed a couple other small type issues. Please use the following release https://github.com/ryandrewjohnson/react-localize-redux/releases/tag/v2.13.5

**Comment by Codeluck** [comment]
@ryandrewjohnson, good job! Now it works like a charm! Thank you.
