### ISSUE TITLE
localize type definition is not consistent with the example

### ISSUE THREAD

**Issue by acerola1** [ryandrewjohnson/react-localize-redux#35]
If I try the following example in TypeScript from [Medium](https://medium.com/@ryandrewjohnson/adding-multi-language-support-to-your-react-redux-app-cf6e64250050):

```
import { localize } from 'react-localize-redux';

const App = (props) => (
  ...
);

// if you use localize make sure to pass the name of the slice
// that localeReducer was attached to.
export default localize(App, 'locale');
```

I get the following typescript error:

> error TS2345: Argument of type '(props: any) => Element' is not assignable to parameter of type 'ReactElement<any>'.
>   Property 'type' is missing in type '(props: any) => Element'.

I think localize typescript definition is not matching with this example.

**Comment by ryandrewjohnson** [comment]
@acerola1 if you have some time you mind taking a look at the typescript def and see if you can get it working with your project? If you’re able to find a solution and submit a PR I can get that published quicker. I’ve done the project in Flow do testing the TS testing on my end is cumbersome at best.

**Comment by acerola1** [comment]
I just started my first project in React, Redux and TypeScript. All three are new for me.
I can use the connect method to get the translate function for now. I feel sometimes Typescript just slows me down. I do not use its full capabilities. So I think I'm not the right person for this task yet. But thanks for this package it is up and running now.

**Comment by ryandrewjohnson** [comment]
@acerola1 no problem thanks for the heads up. Also you may want to take a look at flow type. I've used both flow type, and TypeScript and I personally find flow type much less cumbersome than TypeScript.

**Comment by ryandrewjohnson** [comment]
@acerola1 as a temp fix until I figure things out with the type definition you can do the following:

```javascript
export default localize(App as any, 'locale');
```

**Comment by acerola1** [comment]
Thanks, it works

**Comment by ryandrewjohnson** [comment]
@acerola1 the latest release now has official fix so you can stop using any.
