### ISSUE TITLE
Persist active language?

### ISSUE THREAD

**Issue by rockia** [ryandrewjohnson/react-localize-redux#37]
Hello Ryan, we have the `react-localize-redux` working in our project but currently we encounter an issue. If the user switch the language from `English` to `French`, he/she can view the French version of the website all the way util when they refresh the website.

Every time they refresh the website, the router will initialize the language again with the defaultLanguage (in our case it's English). 
We saw that when action `@@localize/SET_ACTIVE_LANGUAGE` was called, the payload `{languageCode:"fr"}` was sent,  but it's not in the redux store. 

Is there a way to persist the chosen language? We have redux-persist set up already, if the languageCode is saved anywhere, we can pick it up again and use it as the defaultLanguage when next time we initialize the localication.

**Comment by ryandrewjohnson** [comment]
@rockia I have added a FAQ question to answer this on the official docs that should answer your question.

[How do I persist active language?](https://ryandrewjohnson.github.io/react-localize-redux/faq/#how-do-i-persist-active-language)

**Comment by rockia** [comment]
Never thought of using the native method. Thanks @ryandrewjohnson ! Localisation fully up and running, will deploy to production in our next release. Thanks so much for this awesome library and support for the last two weeks! Have a great upcoming Christmas, eh?
