### ISSUE TITLE
TypeError with selector getActiveLanguage 

### ISSUE THREAD

**Issue by tom3012** [ryandrewjohnson/react-localize-redux#4]
I'm getting an error when using the selector getActiveLanguage: `Uncaught TypeError: (0 , _reactLocalizeRedux.getActiveLanguage) is not a function`.

Not sure but have you forgotten to export `getActiveLanguage` at `index.js`? It's only working after importing from `lib/modules/locale` or after adding following to `index.js:`

```
Object.defineProperty(exports, 'getActiveLanguage', {
  enumerable: true,
  get: function get() {
    return _locale.getActiveLanguage;
  }
});
```

**Comment by ryandrewjohnson** [comment]
@tom3012 thanks for catching this .. I've just pushed a new release that should fix this issue.

**Comment by tom3012** [comment]
Nice 👍
