### ISSUE TITLE
'.code' is undefined

### ISSUE THREAD

**Issue by pardonmeme** [ryandrewjohnson/react-localize-redux#41]
So, from time to time something breaks and my web app crashes cause of `".code' `is undefined exception.
I noticed that redux at this point is not even launching the `"@@localize/INITIALIZE"` but still adds languages and launches the `"@@localize/ADD_TRANSLATION_FOR_LANGUAGE"`

I tried to put the locale into localstorage to maybe perhaps avoid the undefined `'.code' `which occurs at `"es/locale.js"` => `var activeLanguageCode = activeLanguage.code;` and read the stored locale with store.subscribe but it did not helped at all, `'.code'` error is still happening.

I just followed the documentation, so I'm not sure what is going on 
This is how I'm dispatching it

```
store.dispatch(initialize([
    { name: 'English', code: 'en-US' },
    { name: 'German', code: 'de-DE' }
]))

store.dispatch(addTranslationForLanguage(settings.en_US, 'en-US'))
store.dispatch(addTranslationForLanguage(settings.de_DE, 'de-DE'))
```

![akzqlhruticqsbq9couo6w](https://user-images.githubusercontent.com/35489260/34986864-7bb86898-fab9-11e7-9c1b-913f5b642af3.png)
![5_krby9qsfu2y6tj-yfaha](https://user-images.githubusercontent.com/35489260/34986898-9e86d062-fab9-11e7-962f-b91ae582c846.png)
![m1dmpg7gr7sbpygyvjqitq](https://user-images.githubusercontent.com/35489260/34986950-c5ea9a3a-fab9-11e7-9d00-ea4a345ead2d.png)

**Comment by DarkSmile92** [comment]
I am having the same issue. Coming from:
react-localize-redux\lib\locale.js
```
var getTranslationsForActiveLanguage = exports.getTranslationsForActiveLanguage = translationsEqualSelector(getActiveLanguage, getLanguages, getTranslations, function (activeLanguage, languages, translations) {
  console.log('Active Language: ',activeLanguage); // UNDEFINDED!
  var activeLanguageCode = activeLanguage.code;

  var activeLanguageIndex = (0, _utils.getIndexForLanguageCode)(activeLanguageCode, languages);
  return Object.keys(translations).reduce(function (prev, key) {
    return _extends({}, prev, _defineProperty({}, key, translations[key][activeLanguageIndex]));
  }, {});
});
```

You are right @ryandrewjohnson , none of the languages made it into the redux store.
I called "dispatch" but not on my store object. When I changed it to call dispatch on my store object right after creation, it worked!

```
const store = createStore(
    ...
  );

  store.dispatch(setActiveLanguage('en'));
  store.dispatch(initialize(languages, { defaultLanguage: 'en' }));
  store.dispatch(addTranslationForLanguage(transEnUs, 'en'));
  store.dispatch(addTranslationForLanguage(transDe, 'de'));
```

**Comment by ryandrewjohnson** [comment]
@DarkSmile92 to confirm... it sound like you've fixed your issue?

**Comment by DarkSmile92** [comment]
@ryandrewjohnson yes I solved mine. Hope this helps @pardonmeme with his.

**Comment by ryandrewjohnson** [comment]
Just to add to what @DarkSmile92 posted in case it helps someone else...

The `dispatch` prop can be called directly by store, but more often than not you will be calling `dispatch` from one of your components. It's important to remember that as soon as you `connect` a component `dispatch` is added to it's props directly. If you're already using connect though you will more than likely want to add your action creators using `mapDispatchToProps` like so:

```javascript
class App extends Component {

  componentWillMount() {
    /** 
     * NOTE: you don't need to call setActiveLanguage here...
     * 1. you shouldn't call it before initialize is called
     * 2. By default initialize will set the first language as your active language, you only need to 
          pass defaultLanguage if it's different than the first language in your languages array.
     */
    // dispatch(setActiveLanguage('en')); 
    
    // now the action creators are available in props, and have been wrapped with dispatch by connect
    this.props.initialize(languages); 
    this.props.addTranslationForLanguage(transEnUs, 'en');
    this.props.addTranslationForLanguage(transDe, 'de');
  }
}

// see mapDispatchToProps argument in react-redux https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments
const mapDispatchToProps = {
  initialize,
  addTranslationForLanguage
};

export default connect(null, mapDispatchToProps)(App);
```

@pardonmeme since I haven't heard back from you I'm going to assume this issue is settled. If you find you're still having issues feel free to comment.
