### ISSUE TITLE
missingTranslationMsg option should be optional in Typescript type declarations.

### ISSUE THREAD

**Issue by sirthomasbayes** [ryandrewjohnson/react-localize-redux#44]
[missingTranslationMsg](https://github.com/ryandrewjohnson/react-localize-redux/blob/a39fb1b19b21d363e7732b386d2fcc4a97be11e5/src/index.d.ts#L29) option on Options type should probably be optional.

**Comment by ryandrewjohnson** [comment]
@sirthomasbayes fixed thanks for the heads up.
