### ISSUE TITLE
Fix broken "pass multiple translations to components" link in docs 

### ISSUE THREAD

**Issue by ryandrewjohnson** [ryandrewjohnson/react-localize-redux#47]
At the bottom of the [Getting Started](https://ryandrewjohnson.github.io/react-localize-redux/getting-started/) page
![image](https://user-images.githubusercontent.com/3419547/35425016-ba453d2a-0225-11e8-831a-c50b7a95c0b5.png)

**Comment by marc-ed-raffalli** [comment]
Please review https://github.com/ryandrewjohnson/react-localize-redux/pull/48 for the fix

**Comment by ryandrewjohnson** [comment]
Thanks @marc-ed-raffalli . Confirmed fix in #48.
