### ISSUE TITLE
Throw an error if string variables are not passed to translate.

### ISSUE THREAD

**Issue by neutrinog** [ryandrewjohnson/react-localize-redux#51]
Translation strings can have variables inside them e.g. `"hello":"Hello ${name}"`.

I'd like to have an error thrown if I forget to include the variable `name` when I do something like `translate('hello')`.

**Comment by ryandrewjohnson** [comment]
Thanks for the suggestion, but I'm not sure I agree with this approach. My main concern is that throwing an error may be severe for this particular user error. An uncaught error, especially in React 16, could result in the entire application not working. I would prefer this to be a recoverable error that would allow the application to continue working. For that reason I prefer the current functionality that renders the translation string as is with missing variable name. e.g. `Hello ${name}` would be rendered. 

One option could be to log a warning to the console. If you like this idea let me know or feel free to send a PR with the implementation.

**Comment by neutrinog** [comment]
Good point. Yes I agree an error is probably too aggressive, while a warning would still get the developer's attention without causing too much trouble.

I'd be more than happy to send a PR with that implementation, however I won't have the time for a week or so. If you want to get it done quick that's great. Otherwise I'll see what I can do in about a week.

**Comment by ryandrewjohnson** [comment]
Closing this as there has been no further requests for feature.
