### ISSUE TITLE
How do I translate smth like list of services?

### ISSUE THREAD

**Issue by Nikki1993** [ryandrewjohnson/react-localize-redux#56]
So, traditionally I would create an object smth like this 

```
const obj = [
  {
    id: 1,
    title: 'Massage',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt non sem vel lacinia. Duis suscipit, nibh ut malesuada aliquet, velit est consectetur leo, quis consectetur ante mauris rutrum orci.',
  },
  {
    id: 2,
    title: 'Massage',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt non sem vel lacinia. Duis suscipit, nibh ut malesuada aliquet, velit est consectetur leo, quis consectetur ante mauris rutrum orci.',
  },
  {
    id: 3,
    title: 'Massage',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt non sem vel lacinia. Duis suscipit, nibh ut malesuada aliquet, velit est consectetur leo, quis consectetur ante mauris rutrum orci.',
  },
];
```

and then run my loop

```
const ServicesList = ({ className }) =>
  obj.map(({ title, description, id }) => (
    <div className={className} key={id}>
      <ContentHeader>{title}</ContentHeader>
      <Content>{description}</Content>
    </div>
  ));
```

Problem, however, with translations is that I have no idea how with default methods (without resorting to creating custom data) to pass multiple translations without manually adding them as props 

`<Services {...translate(['ServicesList.Massage.title ...... '])}  />`

The bigger the list, the more manual work I have to do, plus I have to keep in mind if I delete smth to remove it from here as well, which is far from ideal.

Is there any way to do smth like this 

`<Services {...translate(['ServicesList'])}  />`

And then run my .map function on the object to properly loop through translations, without restoring to custom data implementation?

**Comment by Nikki1993** [comment]
So far, the only suitable way I found was to replicate the names in the list as an object and loop through em

```
const services = [
  { key: 1, value: 'Massage' },
  { key: 2, value: 'Face' },
  { key: 3, value: 'Therapy' },
];

const ServicesList = ({ className, translate }) =>
  services.map(({ key, value }) => (
    <div className={className} key={key}>
      <ContentHeader>{translate(`ServicesList.${value}.title`)}</ContentHeader>
      <Content>{translate(`ServicesList.${value}.description`)}</Content>
    </div>
  ));
```

**Comment by ryandrewjohnson** [comment]
Sorry I don't understand the use case from what you've provided. If you're able to provide a link to the full source that may help.

**Comment by ryandrewjohnson** [comment]
Thanks for the update, but the context I needed is still not included in this explanation. If you want my help I will need a working example to look at that shows the entire `react-localize-redux` implementation, with real translation data.

**Comment by ryandrewjohnson** [comment]
I'm going to close this for now as I haven't heard anything further. Feel free to reopen if you're able to provide the requested info.
