### ISSUE TITLE
Failed to compile Cannot find name 'TranslateChildFunction'

### ISSUE THREAD

**Issue by Qolzam** [ryandrewjohnson/react-localize-redux#63]
Not sure why I got failed to compile.

I see `TranslateChildFunction` is inside the file but it can't find the name.
```
/node_modules/react-localize-redux/lib/index.d.ts
(59,23): Cannot find name 'TranslateChildFunction'.
```

**Comment by ryandrewjohnson** [comment]
If you’re using TypeScript and able to fix on your end and submit a PR that’d be great! I’m using flow when developing, so testing the TS definitions are tougher.

If not I’ll have to have a look tomorrow.

**Comment by Qolzam** [comment]
I have created the pull request on #64. It solved my the problems but not sure if it's the best way.  TypeScript can't understand `TranslateChildFunction` function as a type so I have wrote a type for. Also I got error for `Component<TranslateProps>` which complained I can't use `Component` as a value, so I changed it to `React.Component`. Sorry for typo mistake on issue number 😞.

**Comment by ryandrewjohnson** [comment]
Thanks a lot for your help on this one. I ended up having to make even more type fixes, so I just pulled the changes directly from your PR #64. I have published a new version `v2.17.2` which I hoping fixes all the type issues, but I did have to make one change that could result in some breaks. I had to rename the translate's function type which previously was using a type called `Translate` to `TranslateFunction`, as this was causing conflicts with the new Translate component type that also need to be named `Translate`. 

If you could test and let me know if there are any issues that'd be greatly appreciated.

**Comment by Qolzam** [comment]
Perfect 👍 I have just tested and all working well. I greatly appreciate your fast reply and quick fix.

**Comment by ryandrewjohnson** [comment]
Thanks for your help on this one.
