### ISSUE TITLE
Mispelling

### ISSUE THREAD

**Issue by adamdharrington** [ryandrewjohnson/react-localize-redux#65]
@ryandrewjohnson one of our devs noticed a misspelling in one of the action types which is a fairly visible part of the app (all logger output would quote it). Are you happy if I open a PR with a fix or do you think it's something you need to support now? 

Let me know your pref, I'm happy to contribute or to fork and PR if it's something you'd be likely to merge.

Cheers,
Adam

https://github.com/ryandrewjohnson/react-localize-redux/blob/6dcb0fe2cff3339b4e8026cbee589cbf1f32c2c7/src/index.d.ts#L114

**Comment by adamdharrington** [comment]
Cheers Ryan, sorry it took a few days to get around to doing that :nerd_face:
I'm not sure how many people will have bound to the action name in their reducers/tests so I'm not sure how you'd want to version this but here it is anyway.

**Comment by ryandrewjohnson** [comment]
Although the changes are minor they are still technically breaking changes. For that reason the fix will be included in the v3 release. See #71 for more detail. 

Thanks again for your help @adamdharrington.

**Comment by adamdharrington** [comment]
No problemo happy to help, best of luck with v3

**Comment by ryandrewjohnson** [comment]
Now fixed in [v3.0.0](https://github.com/ryandrewjohnson/react-localize-redux/releases/tag/v3.0.0).
