### ISSUE TITLE
Moving to version 3.0

### ISSUE THREAD

**Issue by ryandrewjohnson** [ryandrewjohnson/react-localize-redux#67]
The [next major release](https://github.com/ryandrewjohnson/react-localize-redux/tree/v3) is in active development with the biggest update being the removal of the dependency on redux. By leveraging [React's new Context API](https://reactjs.org/docs/context.html) the library will now work without redux, while still providing the option to use redux for those users using it in their app.

-------

#### Release plan:

✅ [release-candidate - READY!!!](https://github.com/ryandrewjohnson/react-localize-redux/issues/67#issuecomment-384493024)
⬜ release v3.0.0

-------

#### Todo for release:

✅ should work without redux by default
✅ should work with redux if store provided to `LocalizeProvider`
✅ [option to show default language on missing translation](https://github.com/ryandrewjohnson/react-localize-redux/issues/36#issuecomment-376728723)
✅ correct spelling for add language action #71 
✅ [update documentation ](https://ryandrewjohnson.github.io/react-localize-docs/)
✅ battle test new TypeScript definition #69 
✅ update examples 
✅ [document breaking changes](https://github.com/ryandrewjohnson/react-localize-redux/blob/v3/CHANGELOG.md)
✅ provide [migration guide](https://github.com/ryandrewjohnson/react-localize-redux/blob/v3/MIGRATING.md)

-------------

#### What's changed?

See official [change log](https://github.com/ryandrewjohnson/react-localize-redux/blob/v3/CHANGELOG.md).

**Comment by ryandrewjohnson** [comment]
The release candidate is ready for those that wish to try out `v3.0.0`.

To Install:
```
npm install react-localize-redux@next --save
```

The official docs for the new version are still in the works, but for now be sure to have a look at [the basic example](https://github.com/ryandrewjohnson/react-localize-redux/tree/v3/examples/basic) in v3 branch. It has an example app which gives a basic implementation demo. 

To run the basic example, run the following from the root of directory:
```
npm install
npm start
```

If you are coming from `v2.x.x` a migration guide to go from v2 to v3 is in the works as well. 

Lastly if you find any bugs please open an issue, and be sure to mention the release candidate version you are on.

**Comment by priyankmtr** [comment]
i am using "react-localize-redux": "^3.0.0-rc3". but i could not find `<LocalizeProvider /> `as mentioned in given office docs link. BTW, basic example link is also not working.

**Comment by ryandrewjohnson** [comment]
@priyankmtr can you elaborate on what you mean by "I could not find"? I just installed the `react-localize-redux": "^3.0.0-rc3` and ran the demo, and it appears to work fine. 

Also I've updated the broken basic example link.

**Comment by thchia** [comment]
@priyankmtr are you sure that you have installed the library? It doesn't show up in your dependencies, and if you use npm > v5 it should autosave.

**Comment by ryandrewjohnson** [comment]
@thchia if you have time to do a PR with some tests covering the issue that would be much appreciated. I'm just getting things wrapped up with the v3.0 launch, so if you're able to tackle this before I release on Monday that'd be amazing.

**Comment by thchia** [comment]
@ryandrewjohnson opened in #79. I appreciate you accommodating my contribution efforts 😄

**Comment by ryandrewjohnson** [comment]
[v3.0.0 now released!!](https://github.com/ryandrewjohnson/react-localize-redux/releases/tag/v3.0.0)
