### ISSUE TITLE
Translate class import issue with TypeScript

### ISSUE THREAD

**Issue by gnyekhelyi** [ryandrewjohnson/react-localize-redux#68]
`import { Translate } from 'react-localize-redux';`
Throws:
`Module '".../node_modules/react-localize-redux/lib/index"' has no exported member 'Translate'.`

`import Translate from 'react-localize-redux';`
Throws:
`"export 'default' (imported as 'Translate') was not found in 'react-localize-redux'`

`import * as Translate from 'react-localize-redux';`
Throws:
`JSX element type 'Translate' does not have any construct or call signatures.`

Modifying
`export default class Translate extends ReactComponent<TranslateProps> {}`
to
`export class Translate extends ReactComponent<TranslateProps> {}`
in index.ts.d fixes the issue for me, I can use the following syntax to import Translate without any errors:
`import { Translate } from 'react-localize-redux';`

**Comment by ryandrewjohnson** [comment]
@gnyekhelyi what version of react-localize-redux you using? Also are you using Typescript, and if so which version?

**Comment by gnyekhelyi** [comment]
I'm using  react-localize-redux 2.17.3 and typescript 2.7.2.

[package.json.txt](https://github.com/ryandrewjohnson/react-localize-redux/files/1895036/package.json.txt)

**Comment by ryandrewjohnson** [comment]
K problem is the fix I made to make in `2.17.3` didn't make it in. Currently the TS definition incorrectly exports Translate as default, which is incorrect.

```javascript
// current index.d.ts has this...
export class Translate extends ReactComponent<TranslateProps> {}

// should be this...
export Translate extends ReactComponent<TranslateProps> {}
```
I have the fix, but I won't be able to publish until this evening.

**Comment by gnyekhelyi** [comment]
Ok, thank you!

**Comment by ryandrewjohnson** [comment]
@gnyekhelyi let me know if you have any interest in helping with #69.

**Comment by RikuVan** [comment]
yep I had the same issue. Seems ok, although I am still refactoring now to update with the new api.

**Comment by ryandrewjohnson** [comment]
Closing this issue based on RikuVan’s feedback.
