### ISSUE TITLE
Help me! support TypeScript definition

### ISSUE THREAD

**Issue by ryandrewjohnson** [ryandrewjohnson/react-localize-redux#69]
This library uses [flow](https://flow.org/) for typings so it's easy enough for me to test that flow types are working as expected during development.

I have also done my best to support TypeScript as well by including a type definition with this library, but supporting this has become problematic. Since I'm not using TS for development I feel I don't get the proper test coverage before releasing. 

What I'm hoping is that someone who is currently using `react-localize-redux` in their TypeScript project would be willing to help out with keeping the TS type defs up to date.

**Comment by ryandrewjohnson** [comment]
@Porges thanks for having a look at this. Can you submit a PR with this fix when you get a chance?

**Comment by BobaFatale** [comment]
I also ran in to this error while working on a project so I have put up a PR, I hope that is okay.
Thanks so much @Porges for the solution

**Comment by ryandrewjohnson** [comment]
Closing this as I'll be moving the project over from Flow to TypeScript as part of #140
