### ISSUE TITLE
Block console logs

### ISSUE THREAD

**Issue by simoberny** [ryandrewjohnson/react-localize-redux#83]
Neither a bug nor a feature request but i'am wondering if there's a way to suppress all the localization action logs in the console. 

When i change language i got 5/6 log message, one for every component with localize. 
Despite from this the library works like a charm

react-localize-redux 3.0.1

**Comment by ryandrewjohnson** [comment]
This is from a `console.log` that was left in `LcoalizeProvider` from debugging, and should be removed. I don't have time to get to it tonight, but if you can submit a PR with that line removed I should be able to publish tomorrow.

**Comment by ryandrewjohnson** [comment]
Fixed and published in `v3.0.2`.
