### ISSUE TITLE
How to translate outside of react component? 

### ISSUE THREAD

**Issue by achen0115** [ryandrewjohnson/react-localize-redux#90]
**Do you want to request a _feature_ or report a _bug_?**
_question_ / _feature_

**How to translate outside of react component?**
I wonder if there is a better way to translate strings outside of react components instead of passing translate function every time.

**Which versions of `react` and `react-localize-redux` are you using?**
react 16.4.0
react-localize-redux 2.17.5

**Comment by ryandrewjohnson** [comment]
I recommend looking at [v3.0](https://ryandrewjohnson.github.io/react-localize-redux-docs/) as that is the latest greatest, and will offer you the most amount of options. 

If upgrading to a major release is not an option then look at `v2.17.5`, which includes the [Translate](https://ryandrewjohnson.github.io/react-localize-redux/api/translate/) component as an option for inserting translations.

Either of these options should meet your request.
