### ISSUE TITLE
Disable Action Logging

### ISSUE THREAD

**Issue by colbyfayock** [ryandrewjohnson/react-localize-redux#94]
**Do you want to request a _feature_ or report a _bug_?**
Add an option to disable client logging

**What is the current behavior?**
Logs actions of LocalizeProvider

![image](https://user-images.githubusercontent.com/1045274/41542685-82fd699e-72e3-11e8-8035-dc35a9c8079c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
No logging in a production application

**Which versions of `react` and `react-localize-redux` are you using?**
 - react: 16.4.0
 - react-localize-redux: 3.0.1

**Comment by ryandrewjohnson** [comment]
If you bump up to `v3.1.1` this is gone. 
https://github.com/ryandrewjohnson/react-localize-redux/commit/5dc360c3dd61e005219e427edbee46d9cc676547

**Comment by colbyfayock** [comment]
that worked 👌 ty
